FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Exposer le port
EXPOSE 3002

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev", "--", "--host"]
